name: emotion

dependencies:
  - python=3.6.9
  - pandas=0.25.0
  - numpy=1.16.4
  - matplotlib=3.1.1
  - jupyter
  - ipykernel
  - tensorflow
  - keras
  - opencv
  - scikit-learn
  - h5py
  - pip:
    - imutils